name: Deploy Functions to Firebase

on:
  push:
    branches: 
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: ""

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: |
          cd functions
          npm ci
          npm run build
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v11.22.0
        working-directory: ./functions
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}