name: ESLint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dashboard dependencies
        run: npm ci
      - name: Install cloud function dependencies
        run: |
          cd functions
          npm ci
      - name: Run ESLint
        run: npm run lint